import { CategoryResult } from '../types';

export function parseQuarterDates(quarter: string): {
  startDate: string;
  endDate: string;
} {
  // Parse quarter codes like "2025-Q3"
  const quarterMatch = quarter.match(/(\d{4})-Q([1-4])/);

  if (quarterMatch) {
    const year = parseInt(quarterMatch[1]);
    const q = parseInt(quarterMatch[2]);

    let startDate: Date;
    let endDate: Date;

    switch (q) {
      case 1:
        startDate = new Date(year, 0, 1); // January 1
        endDate = new Date(year, 2, 31); // March 31
        break;
      case 2:
        startDate = new Date(year, 3, 1); // April 1
        endDate = new Date(year, 5, 30); // June 30
        break;
      case 3:
        startDate = new Date(year, 6, 1); // July 1
        endDate = new Date(year, 8, 30); // September 30
        break;
      case 4:
        startDate = new Date(year, 9, 1); // October 1
        endDate = new Date(year, 11, 31); // December 31
        break;
      default:
        // Fallback to current quarter
        return getCurrentQuarterDates();
    }

    return {
      startDate: formatDateForCalendar(startDate),
      endDate: formatDateForCalendar(endDate),
    };
  }

  // Fallback to current quarter if parsing fails
  return getCurrentQuarterDates();
}

function getCurrentQuarterDates(): { startDate: string; endDate: string } {
  const now = new Date();
  const currentYear = now.getFullYear();
  const currentMonth = now.getMonth();

  let startDate: Date;
  let endDate: Date;

  if (currentMonth >= 0 && currentMonth <= 2) {
    // Q1
    startDate = new Date(currentYear, 0, 1); // Jan 1
    endDate = new Date(currentYear, 2, 31); // Mar 31
  } else if (currentMonth >= 3 && currentMonth <= 5) {
    // Q2
    startDate = new Date(currentYear, 3, 1); // Apr 1
    endDate = new Date(currentYear, 5, 30); // Jun 30
  } else if (currentMonth >= 6 && currentMonth <= 8) {
    // Q3
    startDate = new Date(currentYear, 6, 1); // Jul 1
    endDate = new Date(currentYear, 8, 30); // Sep 30
  } else {
    // Q4
    startDate = new Date(currentYear, 9, 1); // Oct 1
    endDate = new Date(currentYear, 11, 31); // Dec 31
  }

  return {
    startDate: formatDateForCalendar(startDate),
    endDate: formatDateForCalendar(endDate),
  };
}

function formatDateForCalendar(date: Date): string {
  return date.toISOString().split('T')[0].replace(/-/g, '');
}

export function generateCalendarUrl(categoryResult: CategoryResult): string {
  const { startDate, endDate } = parseQuarterDates(categoryResult.quarter);
  console.log(startDate, endDate);

  const title = `${categoryResult.source}: ${categoryResult.category}`;
  const dates = `${startDate}/${endDate}`;

  const details = [
    `Quarterly Credit Card Categories`,
    ``,
    `Source: ${categoryResult.source}`,
    `Quarter: ${categoryResult.quarter}`,
    `Categories: ${categoryResult.category}`,
    ``,
    `Remember to activate your quarterly categories for maximum cashback!`,
    ``,
    `Generated by Credit Card Category Tracker`,
  ].join('\\n');

  const params = new URLSearchParams({
    action: 'TEMPLATE',
    text: title,
    dates: dates,
    details: details,
    ctz: 'America/New_York',
  });

  return `https://calendar.google.com/calendar/render?${params.toString()}`;
}

export function getQuarterDisplayName(quarter: string): string {
  // Handle quarter codes like "2025-Q3"
  const quarterMatch = quarter.match(/(\d{4})-Q([1-4])/);

  if (quarterMatch) {
    const year = parseInt(quarterMatch[1]);
    const q = parseInt(quarterMatch[2]);

    let startMonth: string, endMonth: string, endDay: number;

    switch (q) {
      case 1:
        startMonth = 'January';
        endMonth = 'March';
        endDay = 31;
        break;
      case 2:
        startMonth = 'April';
        endMonth = 'June';
        endDay = 30;
        break;
      case 3:
        startMonth = 'July';
        endMonth = 'September';
        endDay = 30;
        break;
      case 4:
        startMonth = 'October';
        endMonth = 'December';
        endDay = 31;
        break;
      default:
        return quarter; // fallback to original string
    }

    return `${startMonth} 1, ${year} - ${endMonth} ${endDay}, ${year}`;
  }

  // Fallback for non-standard quarter formats
  return quarter;
}

export function getNextUpdateDate(): string {
  const now = new Date();
  const nextMonth = new Date(now.getFullYear(), now.getMonth() + 1, 1);
  return nextMonth.toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  });
}
